/*
Copyright 2020 Twitter, Inc.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
https://openapi-generator.tech
Do not edit the class manually.
*/


package com.twitter.clientlib.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TweetEditControls
 */
public class TweetEditControlsTest {
    private final TweetEditControls model = new TweetEditControls();

    /**
     * Model tests for TweetEditControls
     */
    @Test
    public void testTweetEditControls() {
        // TODO: test TweetEditControls
    }

    /**
     * Test the property 'editableUntil'
     */
    @Test
    public void editableUntilTest() {
        // TODO: test editableUntil
    }

    /**
     * Test the property 'editsRemaining'
     */
    @Test
    public void editsRemainingTest() {
        // TODO: test editsRemaining
    }

    /**
     * Test the property 'isEditEligible'
     */
    @Test
    public void isEditEligibleTest() {
        // TODO: test isEditEligible
    }

}
