/*
Copyright 2020 Twitter, Inc.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
https://openapi-generator.tech
Do not edit the class manually.
*/


package com.twitter.clientlib.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.twitter.clientlib.model.TweetCreateRequestGeo;
import com.twitter.clientlib.model.TweetCreateRequestMedia;
import com.twitter.clientlib.model.TweetCreateRequestPoll;
import com.twitter.clientlib.model.TweetCreateRequestReply;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TweetCreateRequest
 */
public class TweetCreateRequestTest {
    private final TweetCreateRequest model = new TweetCreateRequest();

    /**
     * Model tests for TweetCreateRequest
     */
    @Test
    public void testTweetCreateRequest() {
        // TODO: test TweetCreateRequest
    }

    /**
     * Test the property 'directMessageDeepLink'
     */
    @Test
    public void directMessageDeepLinkTest() {
        // TODO: test directMessageDeepLink
    }

    /**
     * Test the property 'forSuperFollowersOnly'
     */
    @Test
    public void forSuperFollowersOnlyTest() {
        // TODO: test forSuperFollowersOnly
    }

    /**
     * Test the property 'geo'
     */
    @Test
    public void geoTest() {
        // TODO: test geo
    }

    /**
     * Test the property 'media'
     */
    @Test
    public void mediaTest() {
        // TODO: test media
    }

    /**
     * Test the property 'poll'
     */
    @Test
    public void pollTest() {
        // TODO: test poll
    }

    /**
     * Test the property 'quoteTweetId'
     */
    @Test
    public void quoteTweetIdTest() {
        // TODO: test quoteTweetId
    }

    /**
     * Test the property 'reply'
     */
    @Test
    public void replyTest() {
        // TODO: test reply
    }

    /**
     * Test the property 'replySettings'
     */
    @Test
    public void replySettingsTest() {
        // TODO: test replySettings
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

}
