/*
Copyright 2020 Twitter, Inc.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
https://openapi-generator.tech
Do not edit the class manually.
*/


package com.twitter.clientlib.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.twitter.clientlib.model.UserEntities;
import com.twitter.clientlib.model.UserPublicMetrics;
import com.twitter.clientlib.model.UserWithheld;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for User
 */
public class UserTest {
    private final User model = new User();

    /**
     * Model tests for User
     */
    @Test
    public void testUser() {
        // TODO: test User
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property '_protected'
     */
    @Test
    public void _protectedTest() {
        // TODO: test _protected
    }

    /**
     * Test the property 'verified'
     */
    @Test
    public void verifiedTest() {
        // TODO: test verified
    }

    /**
     * Test the property 'withheld'
     */
    @Test
    public void withheldTest() {
        // TODO: test withheld
    }

    /**
     * Test the property 'profileImageUrl'
     */
    @Test
    public void profileImageUrlTest() {
        // TODO: test profileImageUrl
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'entities'
     */
    @Test
    public void entitiesTest() {
        // TODO: test entities
    }

    /**
     * Test the property 'pinnedTweetId'
     */
    @Test
    public void pinnedTweetIdTest() {
        // TODO: test pinnedTweetId
    }

    /**
     * Test the property 'publicMetrics'
     */
    @Test
    public void publicMetricsTest() {
        // TODO: test publicMetrics
    }

}
