/*
Copyright 2020 Twitter, Inc.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
https://openapi-generator.tech
Do not edit the class manually.
*/


package com.twitter.clientlib.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.twitter.clientlib.model.VideoAllOfNonPublicMetrics;
import com.twitter.clientlib.model.VideoAllOfOrganicMetrics;
import com.twitter.clientlib.model.VideoAllOfPromotedMetrics;
import com.twitter.clientlib.model.VideoAllOfPublicMetrics;
import com.twitter.clientlib.model.VideoAllOfVariants;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VideoAllOf
 */
public class VideoAllOfTest {
    private final VideoAllOf model = new VideoAllOf();

    /**
     * Model tests for VideoAllOf
     */
    @Test
    public void testVideoAllOf() {
        // TODO: test VideoAllOf
    }

    /**
     * Test the property 'previewImageUrl'
     */
    @Test
    public void previewImageUrlTest() {
        // TODO: test previewImageUrl
    }

    /**
     * Test the property 'durationMs'
     */
    @Test
    public void durationMsTest() {
        // TODO: test durationMs
    }

    /**
     * Test the property 'variants'
     */
    @Test
    public void variantsTest() {
        // TODO: test variants
    }

    /**
     * Test the property 'publicMetrics'
     */
    @Test
    public void publicMetricsTest() {
        // TODO: test publicMetrics
    }

    /**
     * Test the property 'nonPublicMetrics'
     */
    @Test
    public void nonPublicMetricsTest() {
        // TODO: test nonPublicMetrics
    }

    /**
     * Test the property 'organicMetrics'
     */
    @Test
    public void organicMetricsTest() {
        // TODO: test organicMetrics
    }

    /**
     * Test the property 'promotedMetrics'
     */
    @Test
    public void promotedMetricsTest() {
        // TODO: test promotedMetrics
    }

}
