/*
Copyright 2020 Twitter, Inc.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
https://openapi-generator.tech
Do not edit the class manually.
*/


package com.twitter.clientlib.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.twitter.clientlib.model.TweetUnviewable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.twitter.clientlib.JSON;

/**
 * TweetUnviewableSchema
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TweetUnviewableSchema {
  public static final String SERIALIZED_NAME_PUBLIC_TWEET_UNVIEWABLE = "public_tweet_unviewable";
  @SerializedName(SERIALIZED_NAME_PUBLIC_TWEET_UNVIEWABLE)
  private TweetUnviewable publicTweetUnviewable;

  public TweetUnviewableSchema() { 
  }

  public TweetUnviewableSchema publicTweetUnviewable(TweetUnviewable publicTweetUnviewable) {
    
    this.publicTweetUnviewable = publicTweetUnviewable;
    return this;
  }

   /**
   * Get publicTweetUnviewable
   * @return publicTweetUnviewable
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public TweetUnviewable getPublicTweetUnviewable() {
    return publicTweetUnviewable;
  }


  public void setPublicTweetUnviewable(TweetUnviewable publicTweetUnviewable) {
    this.publicTweetUnviewable = publicTweetUnviewable;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TweetUnviewableSchema tweetUnviewableSchema = (TweetUnviewableSchema) o;
    return Objects.equals(this.publicTweetUnviewable, tweetUnviewableSchema.publicTweetUnviewable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(publicTweetUnviewable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TweetUnviewableSchema {\n");
    sb.append("    publicTweetUnviewable: ").append(toIndentedString(publicTweetUnviewable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("public_tweet_unviewable");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("public_tweet_unviewable");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TweetUnviewableSchema
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
     // if (jsonObj == null) {
     //   if (TweetUnviewableSchema.openapiRequiredFields.isEmpty()) {
     //     return;
     //   } else { // has required fields
     //     throw new IllegalArgumentException(String.format("The required field(s) %s in TweetUnviewableSchema is not found in the empty JSON string", TweetUnviewableSchema.openapiRequiredFields.toString()));
     //   }
     // }


      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TweetUnviewableSchema.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `public_tweet_unviewable`
      if (jsonObj.getAsJsonObject("public_tweet_unviewable") != null) {
        TweetUnviewable.validateJsonObject(jsonObj.getAsJsonObject("public_tweet_unviewable"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TweetUnviewableSchema.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TweetUnviewableSchema' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TweetUnviewableSchema> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TweetUnviewableSchema.class));

       return (TypeAdapter<T>) new TypeAdapter<TweetUnviewableSchema>() {
           @Override
           public void write(JsonWriter out, TweetUnviewableSchema value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TweetUnviewableSchema read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TweetUnviewableSchema given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TweetUnviewableSchema
  * @throws IOException if the JSON string is invalid with respect to TweetUnviewableSchema
  */
  public static TweetUnviewableSchema fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TweetUnviewableSchema.class);
  }

 /**
  * Convert an instance of TweetUnviewableSchema to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

