/*
Copyright 2020 Twitter, Inc.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
https://openapi-generator.tech
Do not edit the class manually.
*/


package com.twitter.clientlib;

public class TwitterCredentialsOAuth1 {

  private String twitterConsumerKey;
  private String twitterConsumerSecret;
  private String twitterToken;
  private String twitterTokenSecret;

  public TwitterCredentialsOAuth1(
      String twitterConsumerKey,
      String twitterConsumerSecret,
      String twitterToken,
      String twitterTokenSecret
  ) {
    this.twitterConsumerKey = twitterConsumerKey;
    this.twitterConsumerSecret = twitterConsumerSecret;
    this.twitterToken = twitterToken;
    this.twitterTokenSecret = twitterTokenSecret;
  }

  public String getTwitterConsumerKey() {
    return twitterConsumerKey;
  }

  public void setTwitterConsumerKey(String twitterConsumerKey) {
    this.twitterConsumerKey = twitterConsumerKey;
  }

  public String getTwitterConsumerSecret() {
    return twitterConsumerSecret;
  }

  public void setTwitterConsumerSecret(String twitterConsumerSecret) {
    this.twitterConsumerSecret = twitterConsumerSecret;
  }

  public String getTwitterToken() {
    return twitterToken;
  }

  public void setTwitterToken(String twitterToken) {
    this.twitterToken = twitterToken;
  }

  public String getTwitterTokenSecret() {
    return twitterTokenSecret;
  }

  public void setTwitterTokenSecret(String twitterTokenSecret) {
    this.twitterTokenSecret = twitterTokenSecret;
  }

  public boolean isUserToken() {
    return twitterConsumerKey != null && twitterConsumerSecret != null && twitterToken != null && twitterTokenSecret != null;
  }
}
